[workspace]
resolver = "2"

members = [
    "tc162-rt",
    "defmt-test",
    "tsim-semihosting",
    "probe-semihosting",
    "tc37x-hal", 
]
exclude = ["demo-code","tests_generator"]

[package]
name = "aot_wasm"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
wasmparser = { version = "~0.235.0", default-features = false }
# libm is used to implement some missing mathematical function
# Higher than version 0.2.11 makes some test fail because Aurix doesn't support subnormal floating point
# and libm with higher version assume support as specified by IEEE 754 - 2008
libm = { version = "=0.2.11" } 
defmt = { version = "~0.3.10" }
embedded-alloc = { version = "*" }
fnv = { version = "1.0.7", default-features = false }
indexmap = { version = "2.10.0", default-features = false }
compiler_builtins = { version = "=0.1.120", default-features = false, features = [
    "no-f16-f128",
] }
env_wrapper = { path = "env_wrapper" }
embedded-hal = "0.2.7"

[build-dependencies]
serde_json = "1.0.128"

[features]
tsim = []
board = []
address-masking = []
default = ["address-masking"]


[dev-dependencies]
defmt-test = { path = "defmt-test" }
tc37x-hal = { path = "tc37x-hal" }
tsim-semihosting = { path = "tsim-semihosting" }
probe-semihosting = { path = "probe-semihosting" }
tc162-rt = { path = "tc162-rt", features = ["support-misaligned-access"] }

[profile.release]
opt-level = "z"

[profile.test]
opt-level = "z"

[lib]
harness = false


[[example]]
name = "benchmark"
harness = false

[[example]]
name = "demo"
harness = false

