[tasks.check-tricore-probe]
script_runner = "@duckscript"
install_script = '''
if not which tricore-probe
    trigger_error "Not foundtricore-probe please install following instruction at https://github.com/veecle/tricore-probe"
end
'''

[tasks.check-wast2json]
script_runner = "@duckscript"
install_script = '''
if not which wast2json
    trigger_error "Not found wast2json please install version 3.36 https://github.com/WebAssembly/wabt/releases/tag/1.0.36"
end

'''

[tasks.install-defmt-print]
install_crate = { crate_name = "defmt-print", binary = "defmt-print", test_arg = ["--help"],min_version = "1.0.0" }

[tasks.install-rustfilt]
install_crate = { crate_name = "rustfilt", binary = "rustfilt", test_arg = ["--help"] }

[tasks.install-wasm-tools]
install_crate = { crate_name = "wasm-tools", binary = " wasm-tools", test_arg = ["--version"] }

[tasks.generate-tests]
workspace = false
env = { "WAST2JSON_PATH" = "./wabt-1.0.36/bin/wast2json.exe" }
script_runner='@duckscript'
script='''
if not is_path_exists ./target
    mkdir ./target
end
rm  -r ./target/test_wasm
mkdir ./target/test_wasm
handle = glob_array ./wast_tests/*.wast
for path in ${handle}
    echo ${path}
    wast_file_name = basename ${path}
    split_array = split ${wast_file_name} .
    file_name = array_get ${split_array} 0
    target_path = join_path . target test_wasm ${file_name}.json
    echo ${target_path}
    exec  ${WAST2JSON_PATH} --disable-simd --disable-multi-value --disable-bulk-memory --disable-bulk-memory --disable-saturating-float-to-int --disable-sign-extension ${path} -o ${target_path}
end
'''
dependencies = ["check-wast2json"]

[tasks.check-tsim]
script_runner = "@duckscript"
install_script = '''
if not which tsim16p_e
    trigger_error "Not found tsim16p_e please install it or add containing folder to PATH"
end
'''
 
[tasks.env-windows-tsim]
private = true
workspace = false
condition = { platforms = ["windows"]}
env = { "CARGO_TARGET_TC162_HTC_NONE_RUNNER" = ".\\instruction_simulator_runner.bat" }
dependencies = ["check-tsim"]

[tasks.env-linux-tsim]
private = true
workspace = false
condition = { platforms = ["linux"]}
env = { "CARGO_TARGET_TC162_HTC_NONE_RUNNER" = "./instruction_simulator_runner.sh" } # Create file for linux
dependencies = ["check-tsim"]

[tasks.test-tsim]
workspace = false
command = "cargo"
args = ["test","--features=tsim","${@}"]
dependencies = ["env-linux-tsim","env-windows-tsim","install-defmt-print","install-rustfilt"]

[tasks.run-benchmark-tsim]
workspace = false
command = "cargo"
args = ["run","--example", "benchmark","--features=tsim","${@}"]
dependencies = ["env-linux-tsim","env-windows-tsim","install-defmt-print","install-rustfilt"]

[tasks.run-benchmark-board]
workspace = false
env = { "CARGO_TARGET_TC162_HTC_NONE_RUNNER" = "tricore-probe -c 1" }
command = "cargo"
args = ["run","--example", "benchmark","--features=board","${@}"]
dependencies = ["check-tricore-probe","install-defmt-print"]

[tasks.test-board]
workspace = false
env = { "CARGO_TARGET_TC162_HTC_NONE_RUNNER" = "tricore-probe -c 1" }
command = "cargo"
args = ["test","--features=board","${@}"]
dependencies = ["check-tricore-probe","install-defmt-print"]

[tasks.run-demo-board]
workspace = false
env = { "CARGO_TARGET_TC162_HTC_NONE_RUNNER" = "tricore-probe -c 1" }
command="cargo"
args=["run","--example","demo","--features=board"]
dependencies = ["check-tricore-probe","install-defmt-print"]

[tasks.run-demo-tsim]
workspace = false
command="cargo"
args=["run","--example","demo","--features=tsim"]
dependencies = ["build-demo-code-wasm","env-linux-tsim","env-windows-tsim","install-defmt-print","install-rustfilt"]
